# Generated by Django 4.1.7 on 2023-03-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(choices=[('P', 'Preniuim'), ('S', 'Sylver'), ('G', 'Gold')], max_length=1),
        ),
    ]
